version: '3.8'

services:
  generador-firmas:
    build: .
    container_name: generador_firmas
    ports:
      - "8084:80"
    volumes:
      - ./img:/var/www/html/generador_firmas/img
      - ./logs:/var/log/apache2
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/generador_firmas
    networks:
      - nps_network
    restart: unless-stopped
    depends_on:
      - nps_mysql

  # Servicio de proxy reverso para integrar con la ruta /generador_firmas
  nginx-proxy:
    image: nginx:alpine
    container_name: nginx_proxy_firmas
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    networks:
      - nps_network
    restart: unless-stopped
    depends_on:
      - generador-firmas

networks:
  nps_network:
    external: true
    name: nps_default

volumes:
  img_data:
  logs:
